teamName: kubrix
appName: demo-vm-phac
repoUrl: https://github.com/kubriX-demo/kubrix-demo-vm-phac
appNamespace:
  create: true
  labels:
    kubrix.io/kyverno: kubevirt-rolebinding
stages:
  - name: "test"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        direct: true
  - name: "prod"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - test
